version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-1
    ports:
      - "12181:12181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888
    volumes:
      - ./volumes/zookeeper1/data:/var/lib/zookeeper/data
      - ./volumes/zookeeper1/log:/var/lib/zookeeper/log
  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-2
    ports:
      - "22181:22181"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888
    volumes:
      - ./volumes/zookeeper2/data:/var/lib/zookeeper/data
      - ./volumes/zookeeper2/log:/var/lib/zookeeper/log
  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-3
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888
    volumes:
      - ./volumes/zookeeper3/data:/var/lib/zookeeper/data
      - ./volumes/zookeeper3/log:/var/lib/zookeeper/log
  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:12181,zookeeper-3:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092
    volumes:
      - ./volumes/kafka1/data:/var/lib/kafka/data


  kafka-2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-2
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:12181,zookeeper-3:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092
    volumes:
      - ./volumes/kafka2/data:/var/lib/kafka/data


  kafka-3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-3
    ports:
      - "39092:39092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:12181,zookeeper-2:12181,zookeeper-3:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:39092
    volumes:
      - ./volumes/kafka3/data:/var/lib/kafka/data


  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "9090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:19092,kafka-2:29092,kafka-3:39092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-1:12181,zookeeper-2:12181,zookeeper-3:12181



#  maran-api:
#    container_name: maran-api
#    build: ./kafka
#    environment:
#      - SPRING_PROFILES_ACTIVE=DOCKER_COMPOSE
#    ports:
#      - 8090:8080
#
#  maran-consumer:
#    container_name: maran-consumer
#    build: ./kafka-consumer
#    environment:
#      - SPRING_PROFILES_ACTIVE=DOCKER_COMPOSE
#    ports:
#      - 8091:8088
#
#
#  kafka-shovel:
#    container_name: kafka-shovel-docker
#    build: ./kafka-shovel
#    ports:
#      - 8056:8055
#    depends_on:
#      - kafka-1
#      - kafka-2
#      - kafka-3
#    environment:
#      - KAFKAVERSION=2.1.2
#      - RETRYCOUNT=5
#      - ERRORSUFFIX=ERROR
#      - RETRYPSUFFIX=RETRY
#      - TOPICS=maran:true
#      - BROKERS=kafka-1:19092,kafka-2:29092,kafka-3:39092
#      - DURATION=5
#      - GROUPNAME=compose-kafkashovel
